### ISSUE TITLE
SC2148 when using --shell

### ISSUE THREAD

**Issue by henti** [mschuett/yaml-shellcheck#30]
I'm testing against GitLab CI. 

Our CI uses bash so our shell code uses bashisms. To test this correctly I've switched to:
```
linting_gitlab_ci:
  needs: []
  image: quay.io/mschuette/yaml-shellcheck:latest
  stage: static tests
  script:
    - (find .gitlab-ci.yml; find ci/ -name \*.yaml -or -name \*.yml) | xargs python3 /app/yaml_shellcheck.py -s /bin/bash
```

This in turn gives me:
```
In __root__/opt/ci/templates.yml/.setup_environment/script line 1:
/bin/bash
^-- SC2148 (error): Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
```

The GitLab CI code in question:
```
.setup_environment:
  script:
    - |-
        # CONFIGURING ENVIRONMENT
        if [[ ${CI_COMMIT_BRANCH:-} ]]; then
            echo "## COMMIT PIPELINE ##"
            export BRANCH_NAME="$CI_COMMIT_BRANCH"
        # and for "merge" pipelines we find it here.
        elif [[ ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-} ]]; then
            echo "## MERGE PIPELINE ##"
            export BRANCH_NAME="$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
```

Clearly there is no shell defined, but I would have assumed that adding `-d /bin/bash` to yaml_shellcheck.py would have inferred this.
